"""followers

Revision ID: 527f37985510
Revises: 4635350b5683
Create Date: 2022-06-13 19:22:57.233812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527f37985510'
down_revision = '4635350b5683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
